# Generated by Django 4.2.7 on 2026-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="document_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="product",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("ppt", "PowerPoint (PPT)"),
                    ("doc", "Word Document (DOC)"),
                    ("docx", "Word Document (DOCX)"),
                    ("pptx", "PowerPoint (PPTX)"),
                ],
                default="pdf",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
