# Generated by Django 4.2.7 on 2026-04-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_product_document_file_product_document_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=20)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("iot", "IoT Solutions"),
                            ("drone", "Drone Technology"),
                            ("arvr", "AR/VR Development"),
                            ("software", "Software Development"),
                            ("consulting", "Consulting"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Us Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
