# Generated by Django 4.2.7 on 2026-04-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("app", "App Development"),
                            ("iot", "IoT Solutions"),
                            ("drone", "Drone Technology"),
                            ("arvr", "AR/VR Development"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("client_name", models.CharField(blank=True, max_length=100)),
                (
                    "technologies",
                    models.CharField(
                        help_text="Technologies used (comma separated)", max_length=200
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "case_study_link",
                    models.URLField(
                        blank=True, help_text="Link to detailed case study"
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured projects"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, help_text="Show on website"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
