# Generated by Django 4.2.7 on 2026-04-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("instructor", models.CharField(max_length=100)),
                ("max_participants", models.PositiveIntegerField(default=50)),
                ("registration_deadline", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Workshop",
                "verbose_name_plural": "Workshops",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_label", models.CharField(max_length=200)),
                ("field_name", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("email", "Email"),
                            ("tel", "Phone Number"),
                            ("number", "Number"),
                            ("textarea", "Text Area"),
                            ("select", "Dropdown"),
                            ("radio", "Radio Buttons"),
                            ("checkbox", "Checkboxes"),
                            ("date", "Date"),
                            ("file", "File Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="Comma separated options for select/radio/checkbox",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="notes.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop Form Field",
                "verbose_name_plural": "Workshop Form Fields",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=20)),
                ("form_data", models.JSONField(default=dict)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="notes.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop Registration",
                "verbose_name_plural": "Workshop Registrations",
                "ordering": ["-registered_at"],
                "unique_together": {("workshop", "email")},
            },
        ),
    ]
