# Generated by Django 4.2.7 on 2026-04-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_workshop_workshopform_workshopregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class (e.g., 'fas fa-robot')",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Bootstrap color class (e.g., 'primary', 'success', 'info')",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "ordering": ["order"],
            },
        ),
    ]
