# Generated by Django 4.2.7 on 2026-04-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "drone_type",
                    models.CharField(
                        choices=[
                            ("agriculture", "Agriculture"),
                            ("surveillance", "Surveillance"),
                            ("photography", "Photography"),
                            ("industrial", "Industrial"),
                            ("racing", "Racing"),
                            ("delivery", "Delivery"),
                            ("military", "Military"),
                            ("hobby", "Hobby"),
                        ],
                        default="hobby",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        help_text="Category (e.g., Professional, Entry-level)",
                        max_length=100,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_number", models.CharField(blank=True, max_length=50)),
                (
                    "specifications",
                    models.JSONField(
                        default=dict,
                        help_text="Technical specifications in JSON format",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="drones/"),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        default=list, help_text="Additional gallery images URLs"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="Product video URL"),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="Key features and capabilities"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("out_of_stock", "Out of Stock"),
                            ("discontinued", "Discontinued"),
                            ("pre_order", "Pre-Order"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, help_text="Show on website"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Drone",
                "verbose_name_plural": "Drones",
                "ordering": ["-created_at"],
            },
        ),
    ]
