# Generated by Django 4.2.7 on 2026-04-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_drone"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Phone"),
                            ("chat", "Live Chat"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True, help_text="WhatsApp contact number", max_length=20
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, help_text="Admin response to the support request"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Support",
                "verbose_name_plural": "Customer Support Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
