# Generated by Django 4.2.7 on 2026-04-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_customersupport"),
    ]

    operations = []
