# Generated by Django 4.2.7 on 2026-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0010_alter_category_options_alter_downloadtoken_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsitePopup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Popup/Banner title for admin reference",
                        max_length=200,
                    ),
                ),
                (
                    "popup_type",
                    models.CharField(
                        choices=[
                            ("modal", "Modal Popup"),
                            ("banner", "Image Banner/Poster"),
                        ],
                        default="modal",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Enable/disable popup on website"
                    ),
                ),
                (
                    "poster_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload poster/banner image",
                        null=True,
                        upload_to="popups/",
                    ),
                ),
                (
                    "modal_content",
                    models.TextField(
                        blank=True,
                        help_text="HTML content for modal popup (if type is modal)",
                    ),
                ),
                (
                    "action_link",
                    models.URLField(
                        blank=True, help_text="Button/link URL (optional)", null=True
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        default="Learn More",
                        help_text="Button text",
                        max_length=100,
                    ),
                ),
                (
                    "display_delay",
                    models.PositiveIntegerField(
                        default=2000,
                        help_text="Delay before showing popup (in milliseconds)",
                    ),
                ),
                (
                    "show_once_per_session",
                    models.BooleanField(
                        default=True, help_text="Show only once per browser session"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Website Popup/Poster",
                "verbose_name_plural": "Website Popups/Posters",
                "ordering": ["-created_at"],
            },
        ),
    ]
