# Generated by Django 4.2.7 on 2026-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0011_websitepopup"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="entry_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="workshopregistration",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="workshopregistration",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workshopregistration",
            name="razorpay_order_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workshopregistration",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workshopregistration",
            name="ticket_id",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
