# Generated by Django 5.2.13 on 2026-05-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0012_workshop_entry_fee_workshopregistration_amount_paid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("mobile_number", models.CharField(max_length=15, unique=True)),
                ("whatsapp_number", models.CharField(max_length=15)),
                ("parent_mobile_number", models.CharField(max_length=15)),
                ("father_name", models.CharField(max_length=120)),
                ("mother_name", models.CharField(max_length=120)),
                (
                    "student_class",
                    models.CharField(
                        choices=[("8th", "8th"), ("9th", "9th"), ("10th", "10th")],
                        max_length=10,
                    ),
                ),
                ("school_name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=120)),
                (
                    "medium",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("semi-english", "Semi-English"),
                            ("marathi", "Marathi"),
                            ("hindi", "Hindi"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("student_photo", models.ImageField(upload_to="scholarship_students/")),
                ("registration_datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Scholarship Registration",
                "verbose_name_plural": "Scholarship Registrations",
                "ordering": ["-registration_datetime"],
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("phd", "PhD Projects"),
                    ("mtech", "M.Tech Projects"),
                    ("btech", "B.Tech Projects"),
                    ("web", "Web Development"),
                    ("app", "App Development"),
                    ("iot", "IoT Solutions"),
                    ("drone", "Drone Technology"),
                    ("arvr", "AR/VR Development"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
