# Generated by Django 5.2.13 on 2026-05-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0013_scholarshipregistration_alter_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarshipregistration",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scholarshipregistration",
            name="email_id",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="scholarshipregistration",
            name="parent_guardian_name",
            field=models.CharField(default="", max_length=180),
        ),
        migrations.AddField(
            model_name="scholarshipregistration",
            name="student_name",
            field=models.CharField(default="", max_length=180),
        ),
        migrations.AlterField(
            model_name="scholarshipregistration",
            name="father_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="scholarshipregistration",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="scholarshipregistration",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="scholarshipregistration",
            name="mother_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="scholarshipregistration",
            name="student_class",
            field=models.CharField(
                choices=[("8", "8"), ("9", "9"), ("10", "10")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipregistration",
            name="surname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
