# Generated by Django 5.2.13 on 2026-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0014_scholarshipregistration_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopStudentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=180)),
                ("parent_name", models.CharField(max_length=180)),
                ("mobile", models.CharField(db_index=True, max_length=15)),
                ("school", models.CharField(max_length=200)),
                (
                    "standard",
                    models.CharField(help_text="Class / standard", max_length=20),
                ),
                ("age", models.PositiveIntegerField()),
                ("payment_transaction_id", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Workshop Student Registration",
                "verbose_name_plural": "Workshop Student Registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
