RAZORPAY_PAYMENT_LINK = "https://razorpay.me/@rohitjaydeoshahare"

RAZORPAY_TEST_KEY_ID = "rzp_test_Shf9eHiKKBPcDc"
RAZORPAY_TEST_KEY_SECRET = "APf4dRw2t7olhuhlBRez6Zbj"

RAZORPAY_LIVE_KEY_ID = "rzp_live_XXXXXXXXXXXXXXXX"
RAZORPAY_LIVE_KEY_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ACCOUNT_HOLDER_NAME = "Rohit jaydeo Shahare"
ACCOUNT_NUMBER = "36826496059"
IFSC_CODE = "SBIN0007359"
BANK_NAME = "STATE BANK OF INDIA"

CONTACT_EMAIL = "shaharerohit47@gmail.com"
CONTACT_PHONE = "9359919779"

BUSINESS_NAME = "DPRAMP"
BUSINESS_DESCRIPTION = "Educational PDF Notes and Study Materials"
